### PR TITLE
retry mechanism

### PR DESCRIPTION
**Pull request by wizicer**
1st, I think this change is so fundamental change, need time to prove it works correctly before push to other developers.
2nd, I only test the http part, the websocket part is not working in my machine(to be clear, I simply cannot make websocket works in my docker environment, not this change), and I got not enough time to diagnostic why it fails recently.

IMHO, don't merge for now. This PR is just let you know what I am working on and wish you could let me know your suggestion, I'll test it in my online service with users could test against these codes. Then I'll let you know it's ready (at least the http part).

### CODE REVIEW

**Comment by dkackman** [comment]
interesting. I will take a look. 

for the http bits, have you looked at all at what's built into the framework?

https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/implement-http-call-retries-exponential-backoff-polly

Since Websocket is a persistent connection retry, at lest for transient network issues is likely less important.

**Comment by dkackman** [comment]
As I'm thinking more about this I don't know if retry belongs in this layer. There are edge cases that would need to be considered that might make more sense to reason about in the app layer. Are there ways for an RPC call to look like it failed but it actually succeeded? What's the best thing to do if a `pushtx` request times out?

Open to discussion for sure, but things that should be considered.

**Comment by wizicer** [comment]
Retry in Http or WebSocket is one thing, and retry in Chia API Protocol layer is this thing. Here is for the later one.

Here is my considerations:
1. I got error "newer block .....(blabla)" `error` with `success: false` when calling `GetCoinRecordsByPuzzleHashes` time to time. As my service recently served ten thousands of requests each day, the failure rate are unacceptable.
2. I was switched from another library ChiaApi, which is not maintained and lack of websocket functionality, it works without this issue, I take a look at their source code, and find such retry mechanism: https://github.com/ByronAP/ChiaApi/blob/af8bcad90661468463368e3ff60910ac9e91e4f4/src/ChiaApi/Utils/HttpTools.cs#L129-L154
3. `pushtx` is also retried in that ChiaApi, as my service only serves up to 20 pushes each day, I'm not fully sure this retry mechanism is acceptable, that's why I isolated the `pushtx` without retry.

**Comment by dkackman** [comment]
Got it.  You're going to retry only if you got a response with success equals false.  Right?
That makes sense and addresses what I was thinking.

**Comment by wizicer** [comment]
Correct! 😊

> Got it. You're going to retry only if you got a response with success equals false. Right? That makes sense and addresses what I was thinking.

**Comment by dkackman** [comment]
Cool.  I can think of a way or two that it could be implemented somewhat generally so it can be reused between both http and wss. I'll dig a bit more.

**Review by dkackman — CHANGES_REQUESTED** [review]
- Please have `MaxRetries` property default to 0 so that retry logic is opt-in, not opt-out (especially for current consumers)
- Change `uint? maxRetries = null` parameter on `SendMessage` to `uint maxRetries = 0`. null is effectively zero making the `nullable` redundant

**Comment by wizicer** [comment]
> * Please have `MaxRetries` property default to 0 so that retry logic is opt-in, not opt-out (especially for current consumers)
> * Change `uint? maxRetries = null` parameter on `SendMessage` to `uint maxRetries = 0`. null is effectively zero making the `nullable` redundant

First one is done, for the 2nd one, `null` means using the instance default, while `0` means no retry, I deem it is necessary.

**Comment by dkackman** [comment]
>  the 2nd one, null means using the instance default, while 0 means no retry, I deem it is necessary.

gotcha

**Comment by dkackman** [comment]
I just pushed the NFT stuff for 1.4.0 to main. You may want to merge that into you branch (It includes you HeaderHash addition).

**Comment by wizicer** [comment]
Although the code serves millions of requests(and then I migrated to a database backed solution), however, I'm thinking this should not be a default behavior, various API varied. I just discovered some other APIs also not the best candidate to retry.

Maybe another way outside this library or an extension method would be better.

Would take a look later, as I'm really busy recent months.😭

**Comment by dkackman** [comment]
> Maybe another way outside this library or an extension method would be better.

I do see retry as a cross cutting concern conceptually best handled by something external to the retry target. Like you, busy busy, but I'll see if I can come up with a pattern that might work,

**Pull request closed without merging**
